marinfo:
  time-zone: 'Asia/Seoul'
  nexon-open-api:
    url: http://open.api.nexon.com
    auth-header: x-nxopen-api-key
    auth-key: test_b418572c77e487aaddde3f8a077c03de124a0bf2eea0c29fdee4cf39bac5fa1b200efe6570cbd6c863ef8fdd4b46a849
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/maple_info
    username: maple
    password: new1234!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true